services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8000/health"]
      interval: 20s
      timeout: 3s
      retries: 3